# ===============================
# APLICACION
# ===============================

spring.application.name=gestroproyecto

# ===============================
# MYSQL
# ===============================

spring.datasource.url=jdbc:mysql://127.0.0.1:3306/miapp?createDatabaseIfNotExist=true

spring.datasource.username=root
spring.datasource.password=password

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / HIBERNATE
# ===============================

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ===============================
# THYMELEAF
# ===============================

spring.thymeleaf.cache=false

# ===============================
# SERVER
# ===============================

server.port=8080